### PR TITLE
Stuff for new loom.

### PR DESCRIPTION
**Pull request by covers1624**
Some minor changes, currently in new loom i use reflection to accomplish this.
- Elevates access levels on some classes so i can extend them properly.
- Adds TRACE logging for loading classes from archives, FF is in a forked process, this is for sniffing.
- Moves Gradle script to use MavenPublication, easier for development work as snapshots and mavenLocal can be used.

### CODE REVIEW

**Comment by asiekierka** [comment]
Exposing internals should always be done with great care. Do you *have* to do it this way?

**Comment by modmuss50** [comment]
Maven changes are fine, I can see the reason for making things accessible, but I think getting a 2nd review from @asiekierka on this is required.

These are minor changes, but it may start slipping into bigger changes in the future.

**Comment by covers1624** [comment]
I could merge my threaded decomp stuff over into here, but its kind of specialized to how FF works with new loom, alternatively a factory for ContextUnit's could be used.

Also, just realized i fuged my access levels there, don't pull.

**Comment by covers1624** [comment]
We have decided to do this a bit differently.

**Pull request closed without merging**
